name: Desplegar Frontend a Hostinger

on:
  push:
    branches:
      - main 

jobs:
  web-deploy:
    name: Desplegar carpetas
    runs-on: ubuntu-latest
    steps:
    - name: Obtener código del repo
      uses: actions/checkout@v4

    - name: Subir solo el Front por FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        
        local-dir: ./public/ # Ruta local de los archivos a subir 
        server-dir: ./ # Ruta de destino en el servidor 

        dangerous-clean-html: false # Evita que borre configuraciones internas del servidor
        delete: true # Elimina archivos en el servidor que no estén en el local